### ISSUE TITLE
Toggle off. 

### ISSUE THREAD

**Issue by 0OSeven** [yuri-moens/chaos-plugins-public#2]
I've been religiously using, would there be a way to add a "disable feature" when done slayer task is completed, for some reason, doesn't disconnect ever even when out of combat. Not sure if either an idle for x amount of time disables, or disable on completion. If it's unnecessary and too much work just close, wasn't sure how to mention or recommend it.

**Comment by yuri-moens** [comment]
Toggle off for what plugin? Some plugins stop  themselves once they're done (out of materials for example) although it's not implemented in every plugin. I also don't have a slayer or fighting plugin so if you're talking about the combat helper: it doesn't do any idle checks so it won't keep you logged in. Maybe another plugin is keeping you logged in or you've enabled the Never Log option in UL settings?
